# config/application.yml
defaults: &defaults
  connection:
    time_out:
    private_pem_path: 
  API:
    Spectre:
      client_id: 
      service_secret:
      base_url: https://www.saltedge.com/api/v3/
      
development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults